// Generated by ReScript, PLEASE EDIT WITH CARE


var counter = {
  contents: 0
};

function updateCountText(value) {
  var count = document.querySelector(".count");
  count.innerText = "Count is " + String(value);
  
}

function updateCount(steps) {
  counter.contents = counter.contents + steps | 0;
  return updateCountText(counter.contents);
}

function plusOne(param) {
  return updateCount(1);
}

function minusOne(param) {
  return updateCount(-1);
}

var plusBtn = document.querySelector("#plus-one");

plusBtn.addEventListener("click", plusOne);

var minusBtn = document.querySelector("#minus-one");

minusBtn.addEventListener("click", minusOne);

function getCountClassName(value) {
  if (value > 0) {
    return "count-positive";
  } else if (value < 0) {
    return "count-negative";
  } else {
    return "count-zero";
  }
}

function updateClassName(param) {
  var count = document.querySelector("#count");
  var count_sign = getCountClassName(counter.contents);
  count.className = "count " + count_sign;
  
}

var button_row = document.querySelector(".button-row");

button_row.addEventListener("click", updateClassName);

export {
  counter ,
  updateCountText ,
  updateCount ,
  plusOne ,
  minusOne ,
  plusBtn ,
  minusBtn ,
  getCountClassName ,
  updateClassName ,
  button_row ,
  
}
/* plusBtn Not a pure module */
